---
- name: "Playing with Arch and Ansible"
  hosts: localhost
  become: true
  connection: local

  tasks:
    - name: Install and setup reflector for faster repo access
      import_role:
        name: arch-reflector
      tags:
        - install

    - include_vars: vars/packages.yml

    - name: Install required packages
      import_role:
        name: arch-packages
